### ISSUE TITLE
Bcrypt usage in example given

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/has_secure_password_readme#14]
`def password=(new_password)
    salt = BCrypt::Engine::generate_salt
    hashed = BCrypt::Engine::hash_secret(new_password, salt)
    self.password_digest = salt + hashed
  end`

Why are we doing: `self.password_digest = salt + hashed` instead of `self.password_digest = hashed` ??

 We are already including the salt when we run the following line of code: 
`hashed = BCrypt::Engine::hash_secret(new_password, salt)`

This returns the password hash with the added salt already.

`salt = BCrypt::Engine::generate_salt
 => "$2a$10$HmjXOrXv/uAuxknHRwjfCO"`

`hashed = BCrypt::Engine::hash_secret("password", salt)                                                      
 => "$2a$10$HmjXOrXv/uAuxknHRwjfCO1y/aJrIcVCzPILNcKJXkOS75QlsWVZW" `

So if we do ` salt + hashed`, it would return a string with the salt repeated twice:

`salt + hashed
 => "$2a$10$HmjXOrXv/uAuxknHRwjfCO$2a$10$HmjXOrXv/uAuxknHRwjfCOQw0VksI0KGwgNFotrp0vWKC13k8b6Re"`

Is this what we're aiming towards or is it a mistake? @cernanb

**Comment by cjbrock** [comment]
Hi @Ary770! The goal here in adding the salt again is just to obfuscate as much as possible. You can never be too careful when you're dealing with passwords. 

// Corinna
