### ISSUE TITLE
Incorrect code snippet?

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/has_secure_password_readme#15]
In the final code snippet in the lesson the following method definition is shown:
```  
def create
    user = User.new(user_params).save
end
```
I believe this sets user equal to true or false, which doesn't really make sense. It doesn't affect the code because the `user` variable is never used, but it's confusing. Shouldn't it just be:
```  
def create
    User.create(user_params)
end
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
