### ISSUE TITLE
Small formatting error

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/has_secure_password_readme#16]
See comment below taken from code example in the lesson:

# app/views/user/new.html.erb
<%= form_for :user, url: '/users' do |f| %>
  Username: <%= f.text_field :username %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
<% end %>

[**there needs to be a space or something here to make "# app/controllers/users_controller.rb" italicized and in gray]
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(user_params).save
  end

**Comment by heavenlyboheme** [comment]
Updated and submitted for review. Thanks @arianaberger!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this has been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
