### ISSUE TITLE
Funky colors in last coding example

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/has_secure_password_readme#17]
The colors are funky in the final coding example that appears after this sentence:
"All together, our very secure app might look like this:"

Solution would be to use the usual format of grayed-out paths and black type, etc.

Thank you.

**Comment by heavenlyboheme** [comment]
I corrected this and sent for review. Thanks for the heads up @ValerieHMoore!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
